FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    openssh-client \
    sshpass \
    python3 \
    python3-pip \
    curl \
    git \
    vim \
    && pip3 install ansible

WORKDIR /ansible

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
